services:
  api:
    image: ghcr.io/behzad-moradi/optialgosel:latest
    container_name: optialgosel_api_prod

    # Production values are securely pulled from the cloud environment, NOT typed here
    environment:
      MODEL_PATH: /app/models
      MODEL_REGISTRY: /app/models/registry
      
      # The API points to your external cloud database location
      DB_HOST: ${PROD_DB_HOST}     # e.g., ://aws.com
      DB_PORT: 5432
      DB_NAME: ${PROD_DB_NAME}
      DB_USER: ${PROD_DB_USER}
      DB_PASSWORD: ${PROD_DB_PASSWORD}
      
      SENDER_EMAIL: ${PROD_SENDER_EMAIL}
      APP_PASSWORD: ${PROD_APP_PASSWORD}

    ports:
      - "8000:8000"

    # Always restart the container if the cloud server reboots or if the app crashes
    restart: always

    # Restrict permissions inside the production container for security
    read_only: false
