services:
  postgres:
    image: postgres:18

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: optialgosel_pg

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d optialgosel_pg"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/behzad-moradi/optialgosel:latest

    environment:
      DATABASE_PATH: database/optialgosel.db
      MODEL_PATH: models
      MODEL_REGISTRY: models/registry
      SENDER_EMAIL: test@example.com
      APP_PASSWORD: fake-password

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: optialgosel_pg
      DB_USER: postgres
      DB_PASSWORD: postgres

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped

volumes:
  postgres_data: