name: EC2 IP Test

on:
  push:

jobs:
  get-ip:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::655103423443:role/OptiAlgoSelGitHubActionsRole
          aws-region: ap-southeast-2

      - name: Get EC2 public IP
        run: |
          EC2_IP=$(aws ec2 describe-instances \
            --instance-ids "${{ vars.EC2_INSTANCE_ID }}" \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --output text)

          echo "Current EC2 public IP: $EC2_IP"